version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: db_seletivo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./context/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    volumes:
      - minio-data:/data
  api:
    build:
      context: ./context
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # mapeia a porta 8080 do container para 8081 do host
    container_name: selectivo
    volumes:
      - ./context/tomcat/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh:ro
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - app-network  
    depends_on:
      - postgres
      - minio
    restart: always 
  swagger-bundler:
    image: node:18
    working_dir: /app
    volumes:
      - ../docs:/app/docs
    command: >
      sh -c "
        npm install -g swagger-cli &&
        swagger-cli bundle docs/index.yaml -o docs/default.yaml -t yaml
      "       
  api-docs:
    image: swaggerapi/swagger-ui
    container_name: swagger-api
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /docs/default.yaml
    volumes:
      - ../docs:/docs    
  
networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  minio-data:
