version: "3.8"

services:
  postgres:
    container_name: seletivo-postgres
    image: postgres:15
    environment:
      POSTGRES_DB: db_seletivo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54332:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./context/init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  minio:
    container_name: seletivo-minio
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    volumes:
      - minio-data:/data
  swagger-bundler:
    image: node:18
    working_dir: /app
    volumes:
      - ../docs:/app/docs
    command: >
      sh -c "
        npm install -g swagger-cli &&
        swagger-cli bundle docs/index.yaml -o docs/default.yaml -t yaml
      "       
  api-docs:
    image: swaggerapi/swagger-ui
    container_name: swagger-api
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /docs/default.yaml
    volumes:
      - ../docs:/docs    
  tomcat11:
    image: tomcat:11-jdk17
    container_name: seletivo-tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/conf/context.xml:/usr/local/tomcat/conf/context.xml
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  minio-data:
